// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXb_ixNPgaoL3e5aLk8RxZdopsSucPd0w',
    appId: '1:915975936252:android:3b7a08ba792fb4a358df79',
    messagingSenderId: '915975936252',
    projectId: 'datting-app-7c215',
    storageBucket: 'datting-app-7c215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmt5B259t-n6NyBm5yQFerm0YLa1CpR6U',
    appId: '1:915975936252:ios:4ebc389ad7790cdb58df79',
    messagingSenderId: '915975936252',
    projectId: 'datting-app-7c215',
    storageBucket: 'datting-app-7c215.firebasestorage.app',
    androidClientId: '915975936252-abocpb64r39suscd69dauohonrhiau5r.apps.googleusercontent.com',
    iosClientId: '915975936252-ca3riq3qqflgjqujb8ogpreo4vakdpqt.apps.googleusercontent.com',
    iosBundleId: 'com.akhdan.dattingApp',
  );
}
